import "@/styles/globals.scss";
import clsx from "clsx";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "./providers";

/**
 * [Font] Nunito
 * Use Next Google font
 * If you want to use font from Google, you can use `next/font/google`
 * Then REMOVE the Montserrat font definition below
 */
const nunito = Nunito({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
});

/**
 * [Font] Montserrat
 * Use Local font (store in public)
 * Montserrat font is defined after Nunito, so it will be more priority
 * If you want to use local font from puclic folder, you can use `next/font/local`
 * Then REMOVE the Nunito font definition above
 */
const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat-ExtraLight.ttf',
      weight: '100',
    },
    {
      path: '../../public/fonts/Montserrat-ExtraLight.ttf',
      weight: '200',
    },
    {
      path: '../../public/fonts/Montserrat-Light.ttf',
      weight: '300',
    },
    {
      path: '../../public/fonts/Montserrat-Regular.ttf',
      weight: '400',
    },
    {
      path: '../../public/fonts/Montserrat-Medium.ttf',
      weight: '500',
    },
    {
      path: '../../public/fonts/Montserrat-SemiBold.ttf',
      weight: '600',
    },
    {
      path: '../../public/fonts/Montserrat-Bold.ttf',
      weight: '700',
    },
    {
      path: '../../public/fonts/Montserrat-ExtraBold.ttf',
      weight: '800',
    },
    {
      path: '../../public/fonts/Montserrat-Black.ttf',
      weight: '900',
    },
  ],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          nunito.className,
          nunito.variable,
          montserrat.className,
          montserrat.variable,
          'antialiased'
        )}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
