import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import localFont from 'next/font/local';
import { clsx } from 'clsx';
import '../styles/globals.scss';
import '../styles/hero-ui.css';

/**
 * [Font] Nunito
 * Use Next Google font
 * !Notice: Remove if you use Local font
 */
const nunito = Nunito({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
});

/**
 * [Font] Montserrat
 * Use Local font (store in public)
 * Montserrat font is defined after Nunito, so it will be more priority
 * !Notice: Remove if you use Google font
 */
const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat-ExtraLight.ttf',
      weight: '100',
    },
    {
      path: '../../public/fonts/Montserrat-ExtraLight.ttf',
      weight: '200',
    },
    {
      path: '../../public/fonts/Montserrat-Light.ttf',
      weight: '300',
    },
    {
      path: '../../public/fonts/Montserrat-Regular.ttf',
      weight: '400',
    },
    {
      path: '../../public/fonts/Montserrat-Medium.ttf',
      weight: '500',
    },
    {
      path: '../../public/fonts/Montserrat-SemiBold.ttf',
      weight: '600',
    },
    {
      path: '../../public/fonts/Montserrat-Bold.ttf',
      weight: '700',
    },
    {
      path: '../../public/fonts/Montserrat-ExtraBold.ttf',
      weight: '800',
    },
    {
      path: '../../public/fonts/Montserrat-Black.ttf',
      weight: '900',
    },
  ],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={clsx(
        montserrat.className,
        montserrat.variable,
        nunito.className,
        nunito.variable,
        'h-full antialiased'
      )}
      data-mode='light'>
      <body className='flex min-h-full flex-col'>{children}</body>
    </html>
  );
}
